version: '3.4'

services:

  nginx:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: nginx
    environment:
      - 'NODE_ENV=${NODE_ENV:-production}'
    ports:
      - '3001:80'
    volumes:
      - ./:/srv/app-web:rw

  node:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: node
    environment:
#      Set the user id for node
      - "NODE_USER=${_UID}"
      # Use NODE_USER if defined in the environment, else use the default user id
#      - "NODE_USER=${NODE_USER:-${_UID}}"
    ports:
      - '8080:8080'
    volumes:
      - ./:/srv/app-web:rw
#      - '/srv/app-web/node_modules'
